site_name: Reinforcement Learning
nav:
  - Home: index.md
  - Chapter 1 - Introduction: chapter1/chapter1.md
  # - Chapter 2 - Markov Decision Processes: chapter2/chapter2.md
  # - Chapter 3 - Dynamic Programming: chapter3/chapter3.md
  # - Chapter 4 - Monte Carlo Methods: chapter4/chapter4.md
  # - Chapter 5 - Temportal Difference Learning: chapter5/chapter5.md
  # - Chapter 6 - Function Approximation: chapter6/chapter6.md
  # - Chapter 7 - Policy Gradient Methods: chapter7/chapter7.md
  # - Chapter 8 - Deep Reinforcement Learning: chapter8/chapter8.md
  # - Chapter 9 - Applications in Robotics: chapter9/chapter9.md
  # - Chapter 10 - Applications in Control: chapter10/chapter10.md
  # - Chapter 11 - Applications in Games: chapter11/chapter11.md
  # - Chapter 12 - Applications in [Select Domain]: chapter12/chapter12.md
  # - Chapter 13 - Applications in [Select Domain]: chapter13/chapter13.md
  # - Chapter 14 - Open Challenges: chapter14/chapter14.md
theme:
  name: material
